// automatically generated by the FlatBuffers compiler, do not modify


// @generated

use core::mem;
use core::cmp::Ordering;

extern crate flatbuffers;
use self::flatbuffers::{EndianScalar, Follow};

#[allow(unused_imports, dead_code)]
pub mod wal_schema {

  use core::mem;
  use core::cmp::Ordering;

  extern crate flatbuffers;
  use self::flatbuffers::{EndianScalar, Follow};

#[deprecated(since = "2.0.0", note = "Use associated constants instead. This will no longer be generated in 2021.")]
pub const ENUM_MIN_ORDER_SIDE: i8 = 0;
#[deprecated(since = "2.0.0", note = "Use associated constants instead. This will no longer be generated in 2021.")]
pub const ENUM_MAX_ORDER_SIDE: i8 = 1;
#[deprecated(since = "2.0.0", note = "Use associated constants instead. This will no longer be generated in 2021.")]
#[allow(non_camel_case_types)]
pub const ENUM_VALUES_ORDER_SIDE: [OrderSide; 2] = [
  OrderSide::Buy,
  OrderSide::Sell,
];

#[derive(Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Default)]
#[repr(transparent)]
pub struct OrderSide(pub i8);
#[allow(non_upper_case_globals)]
impl OrderSide {
  pub const Buy: Self = Self(0);
  pub const Sell: Self = Self(1);

  pub const ENUM_MIN: i8 = 0;
  pub const ENUM_MAX: i8 = 1;
  pub const ENUM_VALUES: &'static [Self] = &[
    Self::Buy,
    Self::Sell,
  ];
  /// Returns the variant's name or "" if unknown.
  pub fn variant_name(self) -> Option<&'static str> {
    match self {
      Self::Buy => Some("Buy"),
      Self::Sell => Some("Sell"),
      _ => None,
    }
  }
}
impl core::fmt::Debug for OrderSide {
  fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
    if let Some(name) = self.variant_name() {
      f.write_str(name)
    } else {
      f.write_fmt(format_args!("<UNKNOWN {:?}>", self.0))
    }
  }
}
impl<'a> flatbuffers::Follow<'a> for OrderSide {
  type Inner = Self;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    let b = unsafe { flatbuffers::read_scalar_at::<i8>(buf, loc) };
    Self(b)
  }
}

impl flatbuffers::Push for OrderSide {
    type Output = OrderSide;
    #[inline]
    unsafe fn push(&self, dst: &mut [u8], _written_len: usize) {
        unsafe { flatbuffers::emplace_scalar::<i8>(dst, self.0); }
    }
}

impl flatbuffers::EndianScalar for OrderSide {
  type Scalar = i8;
  #[inline]
  fn to_little_endian(self) -> i8 {
    self.0.to_le()
  }
  #[inline]
  #[allow(clippy::wrong_self_convention)]
  fn from_little_endian(v: i8) -> Self {
    let b = i8::from_le(v);
    Self(b)
  }
}

impl<'a> flatbuffers::Verifiable for OrderSide {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    i8::run_verifier(v, pos)
  }
}

impl flatbuffers::SimpleToVerifyInSlice for OrderSide {}
#[deprecated(since = "2.0.0", note = "Use associated constants instead. This will no longer be generated in 2021.")]
pub const ENUM_MIN_ENTRY_TYPE: u8 = 0;
#[deprecated(since = "2.0.0", note = "Use associated constants instead. This will no longer be generated in 2021.")]
pub const ENUM_MAX_ENTRY_TYPE: u8 = 3;
#[deprecated(since = "2.0.0", note = "Use associated constants instead. This will no longer be generated in 2021.")]
#[allow(non_camel_case_types)]
pub const ENUM_VALUES_ENTRY_TYPE: [EntryType; 4] = [
  EntryType::NONE,
  EntryType::Order,
  EntryType::Cancel,
  EntryType::Trade,
];

#[derive(Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Default)]
#[repr(transparent)]
pub struct EntryType(pub u8);
#[allow(non_upper_case_globals)]
impl EntryType {
  pub const NONE: Self = Self(0);
  pub const Order: Self = Self(1);
  pub const Cancel: Self = Self(2);
  pub const Trade: Self = Self(3);

  pub const ENUM_MIN: u8 = 0;
  pub const ENUM_MAX: u8 = 3;
  pub const ENUM_VALUES: &'static [Self] = &[
    Self::NONE,
    Self::Order,
    Self::Cancel,
    Self::Trade,
  ];
  /// Returns the variant's name or "" if unknown.
  pub fn variant_name(self) -> Option<&'static str> {
    match self {
      Self::NONE => Some("NONE"),
      Self::Order => Some("Order"),
      Self::Cancel => Some("Cancel"),
      Self::Trade => Some("Trade"),
      _ => None,
    }
  }
}
impl core::fmt::Debug for EntryType {
  fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
    if let Some(name) = self.variant_name() {
      f.write_str(name)
    } else {
      f.write_fmt(format_args!("<UNKNOWN {:?}>", self.0))
    }
  }
}
impl<'a> flatbuffers::Follow<'a> for EntryType {
  type Inner = Self;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    let b = unsafe { flatbuffers::read_scalar_at::<u8>(buf, loc) };
    Self(b)
  }
}

impl flatbuffers::Push for EntryType {
    type Output = EntryType;
    #[inline]
    unsafe fn push(&self, dst: &mut [u8], _written_len: usize) {
        unsafe { flatbuffers::emplace_scalar::<u8>(dst, self.0); }
    }
}

impl flatbuffers::EndianScalar for EntryType {
  type Scalar = u8;
  #[inline]
  fn to_little_endian(self) -> u8 {
    self.0.to_le()
  }
  #[inline]
  #[allow(clippy::wrong_self_convention)]
  fn from_little_endian(v: u8) -> Self {
    let b = u8::from_le(v);
    Self(b)
  }
}

impl<'a> flatbuffers::Verifiable for EntryType {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    u8::run_verifier(v, pos)
  }
}

impl flatbuffers::SimpleToVerifyInSlice for EntryType {}
pub struct EntryTypeUnionTableOffset {}

// struct UlidStruct, aligned to 8
#[repr(transparent)]
#[derive(Clone, Copy, PartialEq)]
pub struct UlidStruct(pub [u8; 16]);
impl Default for UlidStruct { 
  fn default() -> Self { 
    Self([0; 16])
  }
}
impl core::fmt::Debug for UlidStruct {
  fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
    f.debug_struct("UlidStruct")
      .field("hi", &self.hi())
      .field("lo", &self.lo())
      .finish()
  }
}

impl flatbuffers::SimpleToVerifyInSlice for UlidStruct {}
impl<'a> flatbuffers::Follow<'a> for UlidStruct {
  type Inner = &'a UlidStruct;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    unsafe { <&'a UlidStruct>::follow(buf, loc) }
  }
}
impl<'a> flatbuffers::Follow<'a> for &'a UlidStruct {
  type Inner = &'a UlidStruct;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    unsafe { flatbuffers::follow_cast_ref::<UlidStruct>(buf, loc) }
  }
}
impl<'b> flatbuffers::Push for UlidStruct {
    type Output = UlidStruct;
    #[inline]
    unsafe fn push(&self, dst: &mut [u8], _written_len: usize) {
        let src = unsafe { ::core::slice::from_raw_parts(self as *const UlidStruct as *const u8, <Self as flatbuffers::Push>::size()) };
        dst.copy_from_slice(src);
    }
    #[inline]
    fn alignment() -> flatbuffers::PushAlignment {
        flatbuffers::PushAlignment::new(8)
    }
}

impl<'a> flatbuffers::Verifiable for UlidStruct {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    v.in_buffer::<Self>(pos)
  }
}

impl<'a> UlidStruct {
  #[allow(clippy::too_many_arguments)]
  pub fn new(
    hi: u64,
    lo: u64,
  ) -> Self {
    let mut s = Self([0; 16]);
    s.set_hi(hi);
    s.set_lo(lo);
    s
  }

  pub fn hi(&self) -> u64 {
    let mut mem = core::mem::MaybeUninit::<<u64 as EndianScalar>::Scalar>::uninit();
    // Safety:
    // Created from a valid Table for this object
    // Which contains a valid value in this slot
    EndianScalar::from_little_endian(unsafe {
      core::ptr::copy_nonoverlapping(
        self.0[0..].as_ptr(),
        mem.as_mut_ptr() as *mut u8,
        core::mem::size_of::<<u64 as EndianScalar>::Scalar>(),
      );
      mem.assume_init()
    })
  }

  pub fn set_hi(&mut self, x: u64) {
    let x_le = x.to_little_endian();
    // Safety:
    // Created from a valid Table for this object
    // Which contains a valid value in this slot
    unsafe {
      core::ptr::copy_nonoverlapping(
        &x_le as *const _ as *const u8,
        self.0[0..].as_mut_ptr(),
        core::mem::size_of::<<u64 as EndianScalar>::Scalar>(),
      );
    }
  }

  pub fn lo(&self) -> u64 {
    let mut mem = core::mem::MaybeUninit::<<u64 as EndianScalar>::Scalar>::uninit();
    // Safety:
    // Created from a valid Table for this object
    // Which contains a valid value in this slot
    EndianScalar::from_little_endian(unsafe {
      core::ptr::copy_nonoverlapping(
        self.0[8..].as_ptr(),
        mem.as_mut_ptr() as *mut u8,
        core::mem::size_of::<<u64 as EndianScalar>::Scalar>(),
      );
      mem.assume_init()
    })
  }

  pub fn set_lo(&mut self, x: u64) {
    let x_le = x.to_little_endian();
    // Safety:
    // Created from a valid Table for this object
    // Which contains a valid value in this slot
    unsafe {
      core::ptr::copy_nonoverlapping(
        &x_le as *const _ as *const u8,
        self.0[8..].as_mut_ptr(),
        core::mem::size_of::<<u64 as EndianScalar>::Scalar>(),
      );
    }
  }

}

pub enum OrderOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct Order<'a> {
  pub _tab: flatbuffers::Table<'a>,
}

impl<'a> flatbuffers::Follow<'a> for Order<'a> {
  type Inner = Order<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: unsafe { flatbuffers::Table::new(buf, loc) } }
  }
}

impl<'a> Order<'a> {
  pub const VT_ORDER_ID: flatbuffers::VOffsetT = 4;
  pub const VT_SYMBOL_ID: flatbuffers::VOffsetT = 6;
  pub const VT_SIDE: flatbuffers::VOffsetT = 8;
  pub const VT_PRICE: flatbuffers::VOffsetT = 10;
  pub const VT_QUANTITY: flatbuffers::VOffsetT = 12;
  pub const VT_USER_ID: flatbuffers::VOffsetT = 14;
  pub const VT_TIMESTAMP: flatbuffers::VOffsetT = 16;

  #[inline]
  pub unsafe fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
    Order { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args OrderArgs<'args>
  ) -> flatbuffers::WIPOffset<Order<'bldr>> {
    let mut builder = OrderBuilder::new(_fbb);
    builder.add_timestamp(args.timestamp);
    builder.add_user_id(args.user_id);
    builder.add_quantity(args.quantity);
    builder.add_price(args.price);
    builder.add_symbol_id(args.symbol_id);
    if let Some(x) = args.order_id { builder.add_order_id(x); }
    builder.add_side(args.side);
    builder.finish()
  }


  #[inline]
  pub fn order_id(&self) -> Option<&'a UlidStruct> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<UlidStruct>(Order::VT_ORDER_ID, None)}
  }
  #[inline]
  pub fn symbol_id(&self) -> u32 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u32>(Order::VT_SYMBOL_ID, Some(0)).unwrap()}
  }
  #[inline]
  pub fn side(&self) -> OrderSide {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<OrderSide>(Order::VT_SIDE, Some(OrderSide::Buy)).unwrap()}
  }
  #[inline]
  pub fn price(&self) -> u64 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u64>(Order::VT_PRICE, Some(0)).unwrap()}
  }
  #[inline]
  pub fn quantity(&self) -> u64 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u64>(Order::VT_QUANTITY, Some(0)).unwrap()}
  }
  #[inline]
  pub fn user_id(&self) -> u64 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u64>(Order::VT_USER_ID, Some(0)).unwrap()}
  }
  #[inline]
  pub fn timestamp(&self) -> u64 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u64>(Order::VT_TIMESTAMP, Some(0)).unwrap()}
  }
}

impl flatbuffers::Verifiable for Order<'_> {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    v.visit_table(pos)?
     .visit_field::<UlidStruct>("order_id", Self::VT_ORDER_ID, false)?
     .visit_field::<u32>("symbol_id", Self::VT_SYMBOL_ID, false)?
     .visit_field::<OrderSide>("side", Self::VT_SIDE, false)?
     .visit_field::<u64>("price", Self::VT_PRICE, false)?
     .visit_field::<u64>("quantity", Self::VT_QUANTITY, false)?
     .visit_field::<u64>("user_id", Self::VT_USER_ID, false)?
     .visit_field::<u64>("timestamp", Self::VT_TIMESTAMP, false)?
     .finish();
    Ok(())
  }
}
pub struct OrderArgs<'a> {
    pub order_id: Option<&'a UlidStruct>,
    pub symbol_id: u32,
    pub side: OrderSide,
    pub price: u64,
    pub quantity: u64,
    pub user_id: u64,
    pub timestamp: u64,
}
impl<'a> Default for OrderArgs<'a> {
  #[inline]
  fn default() -> Self {
    OrderArgs {
      order_id: None,
      symbol_id: 0,
      side: OrderSide::Buy,
      price: 0,
      quantity: 0,
      user_id: 0,
      timestamp: 0,
    }
  }
}

pub struct OrderBuilder<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> {
  fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a, A>,
  start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> OrderBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_order_id(&mut self, order_id: &UlidStruct) {
    self.fbb_.push_slot_always::<&UlidStruct>(Order::VT_ORDER_ID, order_id);
  }
  #[inline]
  pub fn add_symbol_id(&mut self, symbol_id: u32) {
    self.fbb_.push_slot::<u32>(Order::VT_SYMBOL_ID, symbol_id, 0);
  }
  #[inline]
  pub fn add_side(&mut self, side: OrderSide) {
    self.fbb_.push_slot::<OrderSide>(Order::VT_SIDE, side, OrderSide::Buy);
  }
  #[inline]
  pub fn add_price(&mut self, price: u64) {
    self.fbb_.push_slot::<u64>(Order::VT_PRICE, price, 0);
  }
  #[inline]
  pub fn add_quantity(&mut self, quantity: u64) {
    self.fbb_.push_slot::<u64>(Order::VT_QUANTITY, quantity, 0);
  }
  #[inline]
  pub fn add_user_id(&mut self, user_id: u64) {
    self.fbb_.push_slot::<u64>(Order::VT_USER_ID, user_id, 0);
  }
  #[inline]
  pub fn add_timestamp(&mut self, timestamp: u64) {
    self.fbb_.push_slot::<u64>(Order::VT_TIMESTAMP, timestamp, 0);
  }
  #[inline]
  pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a, A>) -> OrderBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    OrderBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> flatbuffers::WIPOffset<Order<'a>> {
    let o = self.fbb_.end_table(self.start_);
    flatbuffers::WIPOffset::new(o.value())
  }
}

impl core::fmt::Debug for Order<'_> {
  fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
    let mut ds = f.debug_struct("Order");
      ds.field("order_id", &self.order_id());
      ds.field("symbol_id", &self.symbol_id());
      ds.field("side", &self.side());
      ds.field("price", &self.price());
      ds.field("quantity", &self.quantity());
      ds.field("user_id", &self.user_id());
      ds.field("timestamp", &self.timestamp());
      ds.finish()
  }
}
pub enum CancelOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct Cancel<'a> {
  pub _tab: flatbuffers::Table<'a>,
}

impl<'a> flatbuffers::Follow<'a> for Cancel<'a> {
  type Inner = Cancel<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: unsafe { flatbuffers::Table::new(buf, loc) } }
  }
}

impl<'a> Cancel<'a> {
  pub const VT_ORDER_ID: flatbuffers::VOffsetT = 4;

  #[inline]
  pub unsafe fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
    Cancel { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args CancelArgs<'args>
  ) -> flatbuffers::WIPOffset<Cancel<'bldr>> {
    let mut builder = CancelBuilder::new(_fbb);
    if let Some(x) = args.order_id { builder.add_order_id(x); }
    builder.finish()
  }


  #[inline]
  pub fn order_id(&self) -> Option<&'a UlidStruct> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<UlidStruct>(Cancel::VT_ORDER_ID, None)}
  }
}

impl flatbuffers::Verifiable for Cancel<'_> {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    v.visit_table(pos)?
     .visit_field::<UlidStruct>("order_id", Self::VT_ORDER_ID, false)?
     .finish();
    Ok(())
  }
}
pub struct CancelArgs<'a> {
    pub order_id: Option<&'a UlidStruct>,
}
impl<'a> Default for CancelArgs<'a> {
  #[inline]
  fn default() -> Self {
    CancelArgs {
      order_id: None,
    }
  }
}

pub struct CancelBuilder<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> {
  fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a, A>,
  start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> CancelBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_order_id(&mut self, order_id: &UlidStruct) {
    self.fbb_.push_slot_always::<&UlidStruct>(Cancel::VT_ORDER_ID, order_id);
  }
  #[inline]
  pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a, A>) -> CancelBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    CancelBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> flatbuffers::WIPOffset<Cancel<'a>> {
    let o = self.fbb_.end_table(self.start_);
    flatbuffers::WIPOffset::new(o.value())
  }
}

impl core::fmt::Debug for Cancel<'_> {
  fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
    let mut ds = f.debug_struct("Cancel");
      ds.field("order_id", &self.order_id());
      ds.finish()
  }
}
pub enum TradeOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct Trade<'a> {
  pub _tab: flatbuffers::Table<'a>,
}

impl<'a> flatbuffers::Follow<'a> for Trade<'a> {
  type Inner = Trade<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: unsafe { flatbuffers::Table::new(buf, loc) } }
  }
}

impl<'a> Trade<'a> {
  pub const VT_MATCH_ID: flatbuffers::VOffsetT = 4;
  pub const VT_BUY_ORDER_ID: flatbuffers::VOffsetT = 6;
  pub const VT_SELL_ORDER_ID: flatbuffers::VOffsetT = 8;
  pub const VT_PRICE: flatbuffers::VOffsetT = 10;
  pub const VT_QUANTITY: flatbuffers::VOffsetT = 12;

  #[inline]
  pub unsafe fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
    Trade { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args TradeArgs<'args>
  ) -> flatbuffers::WIPOffset<Trade<'bldr>> {
    let mut builder = TradeBuilder::new(_fbb);
    builder.add_quantity(args.quantity);
    builder.add_price(args.price);
    builder.add_match_id(args.match_id);
    if let Some(x) = args.sell_order_id { builder.add_sell_order_id(x); }
    if let Some(x) = args.buy_order_id { builder.add_buy_order_id(x); }
    builder.finish()
  }


  #[inline]
  pub fn match_id(&self) -> u64 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u64>(Trade::VT_MATCH_ID, Some(0)).unwrap()}
  }
  #[inline]
  pub fn buy_order_id(&self) -> Option<&'a UlidStruct> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<UlidStruct>(Trade::VT_BUY_ORDER_ID, None)}
  }
  #[inline]
  pub fn sell_order_id(&self) -> Option<&'a UlidStruct> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<UlidStruct>(Trade::VT_SELL_ORDER_ID, None)}
  }
  #[inline]
  pub fn price(&self) -> u64 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u64>(Trade::VT_PRICE, Some(0)).unwrap()}
  }
  #[inline]
  pub fn quantity(&self) -> u64 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u64>(Trade::VT_QUANTITY, Some(0)).unwrap()}
  }
}

impl flatbuffers::Verifiable for Trade<'_> {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    v.visit_table(pos)?
     .visit_field::<u64>("match_id", Self::VT_MATCH_ID, false)?
     .visit_field::<UlidStruct>("buy_order_id", Self::VT_BUY_ORDER_ID, false)?
     .visit_field::<UlidStruct>("sell_order_id", Self::VT_SELL_ORDER_ID, false)?
     .visit_field::<u64>("price", Self::VT_PRICE, false)?
     .visit_field::<u64>("quantity", Self::VT_QUANTITY, false)?
     .finish();
    Ok(())
  }
}
pub struct TradeArgs<'a> {
    pub match_id: u64,
    pub buy_order_id: Option<&'a UlidStruct>,
    pub sell_order_id: Option<&'a UlidStruct>,
    pub price: u64,
    pub quantity: u64,
}
impl<'a> Default for TradeArgs<'a> {
  #[inline]
  fn default() -> Self {
    TradeArgs {
      match_id: 0,
      buy_order_id: None,
      sell_order_id: None,
      price: 0,
      quantity: 0,
    }
  }
}

pub struct TradeBuilder<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> {
  fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a, A>,
  start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> TradeBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_match_id(&mut self, match_id: u64) {
    self.fbb_.push_slot::<u64>(Trade::VT_MATCH_ID, match_id, 0);
  }
  #[inline]
  pub fn add_buy_order_id(&mut self, buy_order_id: &UlidStruct) {
    self.fbb_.push_slot_always::<&UlidStruct>(Trade::VT_BUY_ORDER_ID, buy_order_id);
  }
  #[inline]
  pub fn add_sell_order_id(&mut self, sell_order_id: &UlidStruct) {
    self.fbb_.push_slot_always::<&UlidStruct>(Trade::VT_SELL_ORDER_ID, sell_order_id);
  }
  #[inline]
  pub fn add_price(&mut self, price: u64) {
    self.fbb_.push_slot::<u64>(Trade::VT_PRICE, price, 0);
  }
  #[inline]
  pub fn add_quantity(&mut self, quantity: u64) {
    self.fbb_.push_slot::<u64>(Trade::VT_QUANTITY, quantity, 0);
  }
  #[inline]
  pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a, A>) -> TradeBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    TradeBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> flatbuffers::WIPOffset<Trade<'a>> {
    let o = self.fbb_.end_table(self.start_);
    flatbuffers::WIPOffset::new(o.value())
  }
}

impl core::fmt::Debug for Trade<'_> {
  fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
    let mut ds = f.debug_struct("Trade");
      ds.field("match_id", &self.match_id());
      ds.field("buy_order_id", &self.buy_order_id());
      ds.field("sell_order_id", &self.sell_order_id());
      ds.field("price", &self.price());
      ds.field("quantity", &self.quantity());
      ds.finish()
  }
}
pub enum WalFrameOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct WalFrame<'a> {
  pub _tab: flatbuffers::Table<'a>,
}

impl<'a> flatbuffers::Follow<'a> for WalFrame<'a> {
  type Inner = WalFrame<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: unsafe { flatbuffers::Table::new(buf, loc) } }
  }
}

impl<'a> WalFrame<'a> {
  pub const VT_SEQ: flatbuffers::VOffsetT = 4;
  pub const VT_ENTRY_TYPE: flatbuffers::VOffsetT = 6;
  pub const VT_ENTRY: flatbuffers::VOffsetT = 8;

  #[inline]
  pub unsafe fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
    WalFrame { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args WalFrameArgs
  ) -> flatbuffers::WIPOffset<WalFrame<'bldr>> {
    let mut builder = WalFrameBuilder::new(_fbb);
    builder.add_seq(args.seq);
    if let Some(x) = args.entry { builder.add_entry(x); }
    builder.add_entry_type(args.entry_type);
    builder.finish()
  }


  #[inline]
  pub fn seq(&self) -> u64 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u64>(WalFrame::VT_SEQ, Some(0)).unwrap()}
  }
  #[inline]
  pub fn entry_type(&self) -> EntryType {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<EntryType>(WalFrame::VT_ENTRY_TYPE, Some(EntryType::NONE)).unwrap()}
  }
  #[inline]
  pub fn entry(&self) -> Option<flatbuffers::Table<'a>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<flatbuffers::Table<'a>>>(WalFrame::VT_ENTRY, None)}
  }
  #[inline]
  #[allow(non_snake_case)]
  pub fn entry_as_order(&self) -> Option<Order<'a>> {
    if self.entry_type() == EntryType::Order {
      self.entry().map(|t| {
       // Safety:
       // Created from a valid Table for this object
       // Which contains a valid union in this slot
       unsafe { Order::init_from_table(t) }
     })
    } else {
      None
    }
  }

  #[inline]
  #[allow(non_snake_case)]
  pub fn entry_as_cancel(&self) -> Option<Cancel<'a>> {
    if self.entry_type() == EntryType::Cancel {
      self.entry().map(|t| {
       // Safety:
       // Created from a valid Table for this object
       // Which contains a valid union in this slot
       unsafe { Cancel::init_from_table(t) }
     })
    } else {
      None
    }
  }

  #[inline]
  #[allow(non_snake_case)]
  pub fn entry_as_trade(&self) -> Option<Trade<'a>> {
    if self.entry_type() == EntryType::Trade {
      self.entry().map(|t| {
       // Safety:
       // Created from a valid Table for this object
       // Which contains a valid union in this slot
       unsafe { Trade::init_from_table(t) }
     })
    } else {
      None
    }
  }

}

impl flatbuffers::Verifiable for WalFrame<'_> {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    v.visit_table(pos)?
     .visit_field::<u64>("seq", Self::VT_SEQ, false)?
     .visit_union::<EntryType, _>("entry_type", Self::VT_ENTRY_TYPE, "entry", Self::VT_ENTRY, false, |key, v, pos| {
        match key {
          EntryType::Order => v.verify_union_variant::<flatbuffers::ForwardsUOffset<Order>>("EntryType::Order", pos),
          EntryType::Cancel => v.verify_union_variant::<flatbuffers::ForwardsUOffset<Cancel>>("EntryType::Cancel", pos),
          EntryType::Trade => v.verify_union_variant::<flatbuffers::ForwardsUOffset<Trade>>("EntryType::Trade", pos),
          _ => Ok(()),
        }
     })?
     .finish();
    Ok(())
  }
}
pub struct WalFrameArgs {
    pub seq: u64,
    pub entry_type: EntryType,
    pub entry: Option<flatbuffers::WIPOffset<flatbuffers::UnionWIPOffset>>,
}
impl<'a> Default for WalFrameArgs {
  #[inline]
  fn default() -> Self {
    WalFrameArgs {
      seq: 0,
      entry_type: EntryType::NONE,
      entry: None,
    }
  }
}

pub struct WalFrameBuilder<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> {
  fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a, A>,
  start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> WalFrameBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_seq(&mut self, seq: u64) {
    self.fbb_.push_slot::<u64>(WalFrame::VT_SEQ, seq, 0);
  }
  #[inline]
  pub fn add_entry_type(&mut self, entry_type: EntryType) {
    self.fbb_.push_slot::<EntryType>(WalFrame::VT_ENTRY_TYPE, entry_type, EntryType::NONE);
  }
  #[inline]
  pub fn add_entry(&mut self, entry: flatbuffers::WIPOffset<flatbuffers::UnionWIPOffset>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(WalFrame::VT_ENTRY, entry);
  }
  #[inline]
  pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a, A>) -> WalFrameBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    WalFrameBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> flatbuffers::WIPOffset<WalFrame<'a>> {
    let o = self.fbb_.end_table(self.start_);
    flatbuffers::WIPOffset::new(o.value())
  }
}

impl core::fmt::Debug for WalFrame<'_> {
  fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
    let mut ds = f.debug_struct("WalFrame");
      ds.field("seq", &self.seq());
      ds.field("entry_type", &self.entry_type());
      match self.entry_type() {
        EntryType::Order => {
          if let Some(x) = self.entry_as_order() {
            ds.field("entry", &x)
          } else {
            ds.field("entry", &"InvalidFlatbuffer: Union discriminant does not match value.")
          }
        },
        EntryType::Cancel => {
          if let Some(x) = self.entry_as_cancel() {
            ds.field("entry", &x)
          } else {
            ds.field("entry", &"InvalidFlatbuffer: Union discriminant does not match value.")
          }
        },
        EntryType::Trade => {
          if let Some(x) = self.entry_as_trade() {
            ds.field("entry", &x)
          } else {
            ds.field("entry", &"InvalidFlatbuffer: Union discriminant does not match value.")
          }
        },
        _ => {
          let x: Option<()> = None;
          ds.field("entry", &x)
        },
      };
      ds.finish()
  }
}
#[inline]
/// Verifies that a buffer of bytes contains a `WalFrame`
/// and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_wal_frame_unchecked`.
pub fn root_as_wal_frame(buf: &[u8]) -> Result<WalFrame, flatbuffers::InvalidFlatbuffer> {
  flatbuffers::root::<WalFrame>(buf)
}
#[inline]
/// Verifies that a buffer of bytes contains a size prefixed
/// `WalFrame` and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `size_prefixed_root_as_wal_frame_unchecked`.
pub fn size_prefixed_root_as_wal_frame(buf: &[u8]) -> Result<WalFrame, flatbuffers::InvalidFlatbuffer> {
  flatbuffers::size_prefixed_root::<WalFrame>(buf)
}
#[inline]
/// Verifies, with the given options, that a buffer of bytes
/// contains a `WalFrame` and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_wal_frame_unchecked`.
pub fn root_as_wal_frame_with_opts<'b, 'o>(
  opts: &'o flatbuffers::VerifierOptions,
  buf: &'b [u8],
) -> Result<WalFrame<'b>, flatbuffers::InvalidFlatbuffer> {
  flatbuffers::root_with_opts::<WalFrame<'b>>(opts, buf)
}
#[inline]
/// Verifies, with the given verifier options, that a buffer of
/// bytes contains a size prefixed `WalFrame` and returns
/// it. Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_wal_frame_unchecked`.
pub fn size_prefixed_root_as_wal_frame_with_opts<'b, 'o>(
  opts: &'o flatbuffers::VerifierOptions,
  buf: &'b [u8],
) -> Result<WalFrame<'b>, flatbuffers::InvalidFlatbuffer> {
  flatbuffers::size_prefixed_root_with_opts::<WalFrame<'b>>(opts, buf)
}
#[inline]
/// Assumes, without verification, that a buffer of bytes contains a WalFrame and returns it.
/// # Safety
/// Callers must trust the given bytes do indeed contain a valid `WalFrame`.
pub unsafe fn root_as_wal_frame_unchecked(buf: &[u8]) -> WalFrame {
  unsafe { flatbuffers::root_unchecked::<WalFrame>(buf) }
}
#[inline]
/// Assumes, without verification, that a buffer of bytes contains a size prefixed WalFrame and returns it.
/// # Safety
/// Callers must trust the given bytes do indeed contain a valid size prefixed `WalFrame`.
pub unsafe fn size_prefixed_root_as_wal_frame_unchecked(buf: &[u8]) -> WalFrame {
  unsafe { flatbuffers::size_prefixed_root_unchecked::<WalFrame>(buf) }
}
#[inline]
pub fn finish_wal_frame_buffer<'a, 'b, A: flatbuffers::Allocator + 'a>(
    fbb: &'b mut flatbuffers::FlatBufferBuilder<'a, A>,
    root: flatbuffers::WIPOffset<WalFrame<'a>>) {
  fbb.finish(root, None);
}

#[inline]
pub fn finish_size_prefixed_wal_frame_buffer<'a, 'b, A: flatbuffers::Allocator + 'a>(fbb: &'b mut flatbuffers::FlatBufferBuilder<'a, A>, root: flatbuffers::WIPOffset<WalFrame<'a>>) {
  fbb.finish_size_prefixed(root, None);
}
}  // pub mod wal_schema

